version: '3.4'

services:
  postgresql_database:
    container_name: container-postgres-academia
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=academia
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: container-pgadmin-academia
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=academia@academia.com
      - PGADMIN_DEFAULT_PASSWORD=academia123
    ports:
      - '5050:80'
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  postgresql_database:
  pgadmin:
